
service: telegram-bot

provider:
  name: aws
  runtime: nodejs6.10

functions:
  hello:
    handler: handler.hello

plugins:
- serverless-domain-manager

custom:
  customDomain:
    domainName: www.armved.xyz
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true